pageInfo:
  title: Work Dashboard
appConfig:
  theme: colorful
  layout: auto
  iconSize: large
  startingView: default
  defaultOpeningMethod: sametab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: google
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: sametab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: true
  auth:
    enableGuestAccess: false
    users: []
    enableOidc: false
    oidc:
      adminRole: "false"
      adminGroup: "false"
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
sections:
  - name: Github
    items:
      - title: GitHub
        description: Ikas Github
        url: https://github.com/orgs/ikascom/repositories
        icon: favicon
        target: sametab
        id: 0_611_github
      - title: My Tasks
        description: My Tasks
        url: https://github.com/orgs/ikascom/projects/26/views/1
        icon: favicon
        target: sametab
        id: 1_611_mytasks
      - title: Bug Pool
        description: Ikas Bug Pool
        icon: favicon
        url: https://github.com/orgs/ikascom/projects/20/views/10
        target: sametab
        id: 2_611_bugpool
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Dev Tools
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Jenkins
        description: Ikas Jenkins
        icon: >-
          http://v2jenkins.myikasdev.com:8080/static/f10feadc/images/svgs/logo.svg
        url: http://v2jenkins.myikasdev.com:8080/
        target: sametab
        id: 0_848_jenkins
      - title: Datadog
        description: Ikas Datadog
        icon: >-
          https://imgix.datadoghq.com/img/about/presskit/logo-v/dd_vertical_white.png?auto=format&fit=max&w=847&dpr=2
        url: >-
          https://app.datadoghq.eu/logs?query=&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1749511098979&to_ts=1749511998979&live=true
        target: sametab
        id: 1_848_datadog
      - title: AWS
        description: Ikas AWS
        icon: >-
          https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/512px-Amazon_Web_Services_Logo.svg.png
        url: >-
          https://eu-central-1.console.aws.amazon.com/console/home?region=eu-central-1
        target: sametab
        id: 2_848_aws
      - title: Vercel
        description: Ikas Vercel
        icon: favicon
        url: https://vercel.com/ikascom
        target: sametab
        id: 3_848_vercel
  - name: Misc
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Kolay İK
        description: "Kolay IK "
        icon: favicon
        url: https://app.kolayik.com/home
        target: sametab
        id: 0_396_kolayk
      - title: IT Tools
        description: IT Tools
        icon: favicon
        url: https://it-tools.tech/
        target: sametab
        id: 1_396_ittools
      - title: JSON Escape / Unescape
        icon: favicon
        url: https://www.freeformatter.com/json-escape.html
        target: sametab
        id: 2_396_jsonescapeunescape
